[package]
name = "droplet"
version = "0.0.1"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wgpu = "0.12.0"
winit = "0.26.1"
env_logger = "0.9.0"
log = "0.4.16"
pollster = "0.2.5"
cfg-if = "1"

[dependencies.tokio]
version = "1.17.0"
features = ["full"]
